### PR TITLE
Make package pip installable.

### PR DESCRIPTION
**Pull request by achidlow**
This makes some changes to the setup to allow people to directly install from GitHub using pip.

### CODE REVIEW

**Comment by hlin117** [comment]
Thanks for the PR. However, at the state that this project is in, I don't want people to install this project through pip right now.

* I need a plan forward to make sure Travis works with this directory
* I'd want unit test coverage for this package
* There are some issues, like #12, which have not been resolved yet. I haven't time to address these issues.

**Comment by achidlow** [comment]
The changes to setup.py are necessary changes anyway, pip installation aside. Maybe just merge that change and leave the README unchanged? You can also mark the package as alpha. 

Note that this changeset doesn't make it available on PyPI though (there is plenty of pre-release stuff on there though). And it also means if you run setup.py locally after cloning the repo things will work.

For what its worth, this package has worked out of the box for me so far, so thanks!

**Comment by hlin117** [comment]
Note that unit tests are working again in this package, I've started to let people make more modifications to this package. #22 seems to be taking the lead on this.

@achidlow Would you like to help and review the PR in #22?

**Comment by hlin117** [comment]
This has been taken case of in #25 . Thanks for your time though! I hope you can contribute in the future.

**Pull request closed without merging**
